# Generated by Django 4.2.7 on 2023-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('sex', models.CharField(max_length=10)),
                ('favorite_color', models.CharField(max_length=20)),
            ],
        ),
    ]
