# Generated by Django 4.2.7 on 2023-12-01 12:55

from django.db import migrations

def populate_poll_data(apps, schema_editor):
    Poll = apps.get_model('poll_app', 'Poll')

    # Add your initial data here
    initial_data = [
        {"age": 25, "height": 175, "sex": "Male", "favorite_color": "Blue"},
        {"age": 30, "height": 160, "sex": "Female", "favorite_color": "Green"},
        # Add more entries as needed
    ]

    for data in initial_data:
        Poll.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_poll_data),
    ]