# Generated by Django 4.2.7 on 2023-12-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_auto_20231201_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
